/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnnotationTargetPage } from './annotation-target-page';
import { AnnotationTargetPathGroup } from './annotation-target-path-group';

/**
 * Annotation target drawing.
 * @export
 * @interface AnnotationTargetDrawing
 */
export interface AnnotationTargetDrawing {
    /**
     * 
     * @type {AnnotationTargetPage}
     * @memberof AnnotationTargetDrawing
     */
    'location': AnnotationTargetPage;
    /**
     * List of paths with strokes of the Target.
     * @type {Array<AnnotationTargetPathGroup>}
     * @memberof AnnotationTargetDrawing
     */
    'path_groups': Array<AnnotationTargetPathGroup>;
    /**
     * 
     * @type {string}
     * @memberof AnnotationTargetDrawing
     */
    'type': AnnotationTargetDrawingTypeEnum;
}

type AnnotationTargetDrawingTypeEnum = 'drawing'


