/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppActivityActivityTemplate } from './app-activity-activity-template';
import { AppGroupMini } from './app-group-mini';
import { AppMini } from './app-mini';
import { FileActivityUser } from './file-activity-user';

/**
 * App activity
 * @export
 * @interface AppActivity
 */
export interface AppActivity {
    /**
     * 
     * @type {AppActivityActivityTemplate}
     * @memberof AppActivity
     */
    'activity_template'?: AppActivityActivityTemplate;
    /**
     * 
     * @type {AppMini}
     * @memberof AppActivity
     */
    'app'?: AppMini;
    /**
     * 
     * @type {AppGroupMini}
     * @memberof AppActivity
     */
    'app_group'?: AppGroupMini;
    /**
     * 
     * @type {FileActivityUser}
     * @memberof AppActivity
     */
    'created_by'?: FileActivityUser;
    /**
     * 
     * @type {string}
     * @memberof AppActivity
     */
    'id': string;
    /**
     * When the `app_activity` object was created.
     * @type {string}
     * @memberof AppActivity
     */
    'occurred_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppActivity
     */
    'rendered_text'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppActivity
     */
    'type'?: AppActivityTypeEnum;
}

type AppActivityTypeEnum = 'app_activity'


