/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Additional information about the classification.
 * @export
 * @interface ClassificationsInitializeTemplateRequestFieldsInnerOptionsInnerStaticConfigClassification
 */
export interface ClassificationsInitializeTemplateRequestFieldsInnerOptionsInnerStaticConfigClassification {
    /**
     * A longer description of the classification.
     * @type {string}
     * @memberof ClassificationsInitializeTemplateRequestFieldsInnerOptionsInnerStaticConfigClassification
     */
    'classificationDefinition'?: string;
    /**
     * An identifier used to assign a color to a classification label.  Mapping between a `colorID` and a color may change without notice. Currently, the color mappings are as follows.  * `0`: Yellow * `1`: Orange * `2`: Watermelon red * `3`: Purple rain * `4`: Light blue * `5`: Dark blue * `6`: Light green * `7`: Gray
     * @type {number}
     * @memberof ClassificationsInitializeTemplateRequestFieldsInnerOptionsInnerStaticConfigClassification
     */
    'colorID'?: number;
}

