/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CollaborationAccessibleByAllOf } from './collaboration-accessible-by-all-of';

/**
 * 
 * @export
 * @interface CollaborationAccessibleBy
 */
export interface CollaborationAccessibleBy {
    /**
     * The unique identifier for this object
     * @type {string}
     * @memberof CollaborationAccessibleBy
     */
    'id': string;
    /**
     * `group`
     * @type {string}
     * @memberof CollaborationAccessibleBy
     */
    'type': CollaborationAccessibleByTypeEnum;
    /**
     * The name of the group
     * @type {string}
     * @memberof CollaborationAccessibleBy
     */
    'name'?: string;
    /**
     * The primary email address of this user. If the collaboration status is `pending`, an empty string is returned.
     * @type {string}
     * @memberof CollaborationAccessibleBy
     */
    'login'?: string;
    /**
     * The type of the group.
     * @type {string}
     * @memberof CollaborationAccessibleBy
     */
    'group_type'?: CollaborationAccessibleByGroupTypeEnum;
}

type CollaborationAccessibleByTypeEnum = 'group'
type CollaborationAccessibleByGroupTypeEnum = 'managed_group' | 'all_users_group'


