/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DevicePinner } from './device-pinner';
import { DevicePinnersOrderInner } from './device-pinners-order-inner';

/**
 * A list of device pins
 * @export
 * @interface DevicePinners
 */
export interface DevicePinners {
    /**
     * A list of device pins
     * @type {Array<DevicePinner>}
     * @memberof DevicePinners
     */
    'entries'?: Array<DevicePinner>;
    /**
     * The limit that was used for these entries. This will be the same as the `limit` query parameter unless that value exceeded the maximum value allowed.
     * @type {number}
     * @memberof DevicePinners
     */
    'limit'?: number;
    /**
     * The marker for the start of the next page of results.
     * @type {number}
     * @memberof DevicePinners
     */
    'next_marker'?: number;
    /**
     * The order by which items are returned.
     * @type {Array<DevicePinnersOrderInner>}
     * @memberof DevicePinners
     */
    'order'?: Array<DevicePinnersOrderInner>;
}

