/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Array&lt;string&gt; } from './array&lt;string&gt;';
import { Folder } from './folder';
import { FolderAllOfFolderUploadEmail } from './folder-all-of-folder-upload-email';
import { FolderFullAllOf } from './folder-full-all-of';
import { FolderMini } from './folder-mini';
import { Items } from './items';
import { UserMini } from './user-mini';

/**
 * @type FolderFull
 * A full representation of a folder, as can be returned from any folder API endpoints by default
 * @export
 */
export type FolderFull = Folder & FolderFullAllOf;


