/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Group } from './group';
import { GroupFullAllOf } from './group-full-all-of';

/**
 * @type GroupFull
 * Groups contain a set of users, and can be used in place of users in some operations, such as collaborations.
 * @export
 */
export type GroupFull = Group & GroupFullAllOf;


