/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A base representation of an integration mapping object.
 * @export
 * @interface IntegrationMappingBase
 */
export interface IntegrationMappingBase {
    /**
     * A unique identifier of a folder mapping (part of a composite key together with `integration_type`)
     * @type {string}
     * @memberof IntegrationMappingBase
     */
    'id'?: string;
    /**
     * Identifies the Box partner app, with which the mapping is associated. Currently only supports Slack. (part of the composite key together with `id`)
     * @type {string}
     * @memberof IntegrationMappingBase
     */
    'integration_type'?: IntegrationMappingBaseIntegrationTypeEnum;
}

type IntegrationMappingBaseIntegrationTypeEnum = 'slack'


