/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The schema for an integration mapping mapped item object for type Slack.  Depending if Box for Slack is installed at the org or workspace level, provide **either** `slack_org_id` **or** `slack_workspace_id`. Do not use both parameters at the same time.
 * @export
 * @interface IntegrationMappingPartnerItemSlack
 */
export interface IntegrationMappingPartnerItemSlack {
    /**
     * Type of the mapped item referenced in `id`
     * @type {string}
     * @memberof IntegrationMappingPartnerItemSlack
     */
    'type': IntegrationMappingPartnerItemSlackTypeEnum;
    /**
     * ID of the mapped item (of type referenced in `type`)
     * @type {string}
     * @memberof IntegrationMappingPartnerItemSlack
     */
    'id': string;
    /**
     * ID of the Slack workspace with which the item is associated. Use this parameter if Box for Slack is installed at a workspace level. Do not use `slack_org_id` at the same time.
     * @type {string}
     * @memberof IntegrationMappingPartnerItemSlack
     */
    'slack_workspace_id'?: string | null;
    /**
     * ID of the Slack org with which the item is associated. Use this parameter if Box for Slack is installed at the org level. Do not use `slack_workspace_id` at the same time.
     * @type {string}
     * @memberof IntegrationMappingPartnerItemSlack
     */
    'slack_org_id'?: string | null;
}

type IntegrationMappingPartnerItemSlackTypeEnum = 'channel'


