/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { KeywordSkillCardEntriesInner } from './keyword-skill-card-entries-inner';
import { KeywordSkillCardInvocation } from './keyword-skill-card-invocation';
import { KeywordSkillCardSkill } from './keyword-skill-card-skill';
import { KeywordSkillCardSkillCardTitle } from './keyword-skill-card-skill-card-title';

/**
 * A skill card that contains a set of keywords
 * @export
 * @interface KeywordSkillCard
 */
export interface KeywordSkillCard {
    /**
     * The optional date and time this card was created at.
     * @type {string}
     * @memberof KeywordSkillCard
     */
    'created_at'?: string;
    /**
     * `skill_card`
     * @type {string}
     * @memberof KeywordSkillCard
     */
    'type': KeywordSkillCardTypeEnum;
    /**
     * `keyword`
     * @type {string}
     * @memberof KeywordSkillCard
     */
    'skill_card_type': KeywordSkillCardSkillCardTypeEnum;
    /**
     * 
     * @type {KeywordSkillCardSkillCardTitle}
     * @memberof KeywordSkillCard
     */
    'skill_card_title'?: KeywordSkillCardSkillCardTitle;
    /**
     * 
     * @type {KeywordSkillCardSkill}
     * @memberof KeywordSkillCard
     */
    'skill': KeywordSkillCardSkill;
    /**
     * 
     * @type {KeywordSkillCardInvocation}
     * @memberof KeywordSkillCard
     */
    'invocation': KeywordSkillCardInvocation;
    /**
     * An list of entries in the metadata card.
     * @type {Array<KeywordSkillCardEntriesInner>}
     * @memberof KeywordSkillCard
     */
    'entries': Array<KeywordSkillCardEntriesInner>;
}

type KeywordSkillCardTypeEnum = 'skill_card'
type KeywordSkillCardSkillCardTypeEnum = 'keyword'


