/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The parent folder for this item
 * @export
 * @interface PathCollectionTrashEntriesInner
 */
export interface PathCollectionTrashEntriesInner {
    /**
     * `folder`
     * @type {string}
     * @memberof PathCollectionTrashEntriesInner
     */
    'type'?: PathCollectionTrashEntriesInnerTypeEnum;
    /**
     * The unique identifier that represent a folder.
     * @type {string}
     * @memberof PathCollectionTrashEntriesInner
     */
    'id'?: string;
    /**
     * This field is null for the Trash folder
     * @type {string}
     * @memberof PathCollectionTrashEntriesInner
     */
    'sequence_id'?: string | null;
    /**
     * This field is null for the Trash folder
     * @type {string}
     * @memberof PathCollectionTrashEntriesInner
     */
    'etag'?: string | null;
    /**
     * The name of the Trash folder.
     * @type {string}
     * @memberof PathCollectionTrashEntriesInner
     */
    'name'?: string;
}

type PathCollectionTrashEntriesInnerTypeEnum = 'folder'


