/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The user or group to give access to the item.
 * @export
 * @interface PostCollaborationsRequestAccessibleBy
 */
export interface PostCollaborationsRequestAccessibleBy {
    /**
     * The type of collaborator to invite.
     * @type {string}
     * @memberof PostCollaborationsRequestAccessibleBy
     */
    'type': PostCollaborationsRequestAccessibleByTypeEnum;
    /**
     * The ID of the user or group.  Alternatively, use `login` to specify a user by email address.
     * @type {string}
     * @memberof PostCollaborationsRequestAccessibleBy
     */
    'id'?: string;
    /**
     * The email address of the user to grant access to the item.  Alternatively, use `id` to specify a user by user ID.
     * @type {string}
     * @memberof PostCollaborationsRequestAccessibleBy
     */
    'login'?: string;
}

type PostCollaborationsRequestAccessibleByTypeEnum = 'user' | 'group'


