/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RetentionPoliciesCreatePolicyRequestRetentionLength } from './retention-policies-create-policy-request-retention-length';
import { RetentionPoliciesUpdatePolicyRequestDispositionAction } from './retention-policies-update-policy-request-disposition-action';
import { UserBase } from './user-base';

/**
 * 
 * @export
 * @interface RetentionPoliciesUpdatePolicyRequest
 */
export interface RetentionPoliciesUpdatePolicyRequest {
    /**
     * The additional text description of the retention policy.
     * @type {string}
     * @memberof RetentionPoliciesUpdatePolicyRequest
     */
    'description'?: string | null;
    /**
     * The name for the retention policy
     * @type {string}
     * @memberof RetentionPoliciesUpdatePolicyRequest
     */
    'policy_name'?: string | null;
    /**
     * 
     * @type {RetentionPoliciesUpdatePolicyRequestDispositionAction}
     * @memberof RetentionPoliciesUpdatePolicyRequest
     */
    'disposition_action'?: RetentionPoliciesUpdatePolicyRequestDispositionAction;
    /**
     * Specifies the retention type:  * `modifiable`: You can modify the retention policy. For example, you can add or remove folders, shorten or lengthen the policy duration, or delete the assignment. Use this type if your retention policy is not related to any regulatory purposes. * `non-modifiable`: You can modify the retention policy only in a limited way: add a folder, lengthen the duration, retire the policy, change the disposition action or notification settings. You cannot perform other actions, such as deleting the assignment or shortening the policy duration. Use this type to ensure compliance with regulatory retention policies.  When updating a retention policy, you can use `non-modifiable` type only. You can convert a `modifiable` policy to `non-modifiable`, but not the other way around.
     * @type {string}
     * @memberof RetentionPoliciesUpdatePolicyRequest
     */
    'retention_type'?: string | null;
    /**
     * 
     * @type {RetentionPoliciesCreatePolicyRequestRetentionLength}
     * @memberof RetentionPoliciesUpdatePolicyRequest
     */
    'retention_length'?: RetentionPoliciesCreatePolicyRequestRetentionLength;
    /**
     * Used to retire a retention policy.  If not retiring a policy, do not include this parameter or set it to `null`.
     * @type {string}
     * @memberof RetentionPoliciesUpdatePolicyRequest
     */
    'status'?: string | null;
    /**
     * Determines if the owner of items under the policy can extend the retention when the original retention duration is about to end.
     * @type {boolean}
     * @memberof RetentionPoliciesUpdatePolicyRequest
     */
    'can_owner_extend_retention'?: boolean | null;
    /**
     * Determines if owners and co-owners of items under the policy are notified when the retention duration is about to end.
     * @type {boolean}
     * @memberof RetentionPoliciesUpdatePolicyRequest
     */
    'are_owners_notified'?: boolean | null;
    /**
     * A list of users notified when the retention duration is about to end.
     * @type {Array<UserBase>}
     * @memberof RetentionPoliciesUpdatePolicyRequest
     */
    'custom_notification_recipients'?: Array<UserBase> | null;
}

