/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Counts the retention policy assignments for each item type.
 * @export
 * @interface RetentionPolicyAllOfAssignmentCounts
 */
export interface RetentionPolicyAllOfAssignmentCounts {
    /**
     * The number of enterprise assignments this policy has. The maximum value is 1.
     * @type {number}
     * @memberof RetentionPolicyAllOfAssignmentCounts
     */
    'enterprise'?: number;
    /**
     * The number of folder assignments this policy has.
     * @type {number}
     * @memberof RetentionPolicyAllOfAssignmentCounts
     */
    'folder'?: number;
    /**
     * The number of metadata template assignments this policy has.
     * @type {number}
     * @memberof RetentionPolicyAllOfAssignmentCounts
     */
    'metadata_template'?: number;
}

