/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A list of endpoints for a chunked upload session.
 * @export
 * @interface SessionEndpoints
 */
export interface SessionEndpoints {
    /**
     * The URL to upload parts to
     * @type {string}
     * @memberof SessionEndpoints
     */
    'upload_part'?: string;
    /**
     * The URL used to commit the file
     * @type {string}
     * @memberof SessionEndpoints
     */
    'commit'?: string;
    /**
     * The URL for used to abort the session.
     * @type {string}
     * @memberof SessionEndpoints
     */
    'abort'?: string;
    /**
     * The URL users to list all parts.
     * @type {string}
     * @memberof SessionEndpoints
     */
    'list_parts'?: string;
    /**
     * The URL used to get the status of the upload.
     * @type {string}
     * @memberof SessionEndpoints
     */
    'status'?: string;
    /**
     * The URL used to get the upload log from.
     * @type {string}
     * @memberof SessionEndpoints
     */
    'log_event'?: string;
}

