/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SharedLinksWebLinksUpdateSharedLinkRequestSharedLinkPermissions
 */
export interface SharedLinksWebLinksUpdateSharedLinkRequestSharedLinkPermissions {
    /**
     * If the shared link allows for downloading of files. This can only be set when `access` is set to `open` or `company`.
     * @type {boolean}
     * @memberof SharedLinksWebLinksUpdateSharedLinkRequestSharedLinkPermissions
     */
    'can_download'?: boolean;
    /**
     * If the shared link allows for previewing of files. This value is always `true`. For shared links on folders this also applies to any items in the folder.
     * @type {boolean}
     * @memberof SharedLinksWebLinksUpdateSharedLinkRequestSharedLinkPermissions
     */
    'can_preview'?: boolean;
    /**
     * This value can only be `true` is `type` is `file`.
     * @type {boolean}
     * @memberof SharedLinksWebLinksUpdateSharedLinkRequestSharedLinkPermissions
     */
    'can_edit'?: boolean;
}

