/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ShieldInformationBarrierBase } from './shield-information-barrier-base';
import { ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequestRestrictedSegment } from './shield-information-barrier-segment-restrictions-create-barrier-object-request-restricted-segment';
import { ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequestShieldInformationBarrierSegment } from './shield-information-barrier-segment-restrictions-create-barrier-object-request-shield-information-barrier-segment';

/**
 * 
 * @export
 * @interface ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequest
 */
export interface ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequest {
    /**
     * The type of the shield barrier segment restriction for this member.
     * @type {string}
     * @memberof ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequest
     */
    'type': ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequestTypeEnum;
    /**
     * 
     * @type {ShieldInformationBarrierBase}
     * @memberof ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequest
     */
    'shield_information_barrier'?: ShieldInformationBarrierBase;
    /**
     * 
     * @type {ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequestShieldInformationBarrierSegment}
     * @memberof ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequest
     */
    'shield_information_barrier_segment': ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequestShieldInformationBarrierSegment;
    /**
     * 
     * @type {ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequestRestrictedSegment}
     * @memberof ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequest
     */
    'restricted_segment': ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequestRestrictedSegment;
}

type ShieldInformationBarrierSegmentRestrictionsCreateBarrierObjectRequestTypeEnum = 'shield_information_barrier_segment_restriction'


