/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ShieldInformationBarrierSegmentRestrictionBase } from './shield-information-barrier-segment-restriction-base';
import { ShieldInformationBarrierSegmentRestrictionMiniAllOf } from './shield-information-barrier-segment-restriction-mini-all-of';
import { ShieldInformationBarrierSegmentRestrictionMiniAllOfRestrictedSegment } from './shield-information-barrier-segment-restriction-mini-all-of-restricted-segment';
import { ShieldInformationBarrierSegmentRestrictionMiniAllOfShieldInformationBarrierSegment } from './shield-information-barrier-segment-restriction-mini-all-of-shield-information-barrier-segment';

/**
 * @type ShieldInformationBarrierSegmentRestrictionMini
 * A mini representation of a segment restriction object for the shield information barrier
 * @export
 */
export type ShieldInformationBarrierSegmentRestrictionMini = ShieldInformationBarrierSegmentRestrictionBase & ShieldInformationBarrierSegmentRestrictionMiniAllOf;


