/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Prefill tags are used to prefill placeholders with signer input data. Only one value field can be included.
 * @export
 * @interface SignRequestPrefillTag
 */
export interface SignRequestPrefillTag {
    /**
     * This references the ID of a specific tag contained in a file of the sign request.
     * @type {string}
     * @memberof SignRequestPrefillTag
     */
    'document_tag_id'?: string | null;
    /**
     * Text prefill value
     * @type {string}
     * @memberof SignRequestPrefillTag
     */
    'text_value'?: string | null;
    /**
     * Checkbox prefill value
     * @type {boolean}
     * @memberof SignRequestPrefillTag
     */
    'checkbox_value'?: boolean | null;
    /**
     * Date prefill value
     * @type {string}
     * @memberof SignRequestPrefillTag
     */
    'date_value'?: string | null;
}

