/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FileMini } from './file-mini';

/**
 * List of files that will be signed, which are copies of the original source files. A new version of these files are created as signers sign and can be downloaded at any point in the signing process.
 * @export
 * @interface SignRequestAllOfSignFiles
 */
export interface SignRequestAllOfSignFiles {
    /**
     * 
     * @type {Array<FileMini>}
     * @memberof SignRequestAllOfSignFiles
     */
    'files'?: Array<FileMini>;
    /**
     * Indicates whether the `sign_files` documents are processing and the PDFs may be out of date. A change to any document requires processing on all `sign_files`. We recommended waiting until processing is finished (and this value is true) before downloading the PDFs.
     * @type {boolean}
     * @memberof SignRequestAllOfSignFiles
     */
    'is_ready_for_download'?: boolean;
}

