/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SignRequestSignerInputAllOf
 */
export interface SignRequestSignerInputAllOf {
    /**
     * Type of input
     * @type {string}
     * @memberof SignRequestSignerInputAllOf
     */
    'type'?: SignRequestSignerInputAllOfTypeEnum;
    /**
     * Content type of input
     * @type {string}
     * @memberof SignRequestSignerInputAllOf
     */
    'content_type'?: SignRequestSignerInputAllOfContentTypeEnum;
    /**
     * Index of page that the input is on
     * @type {number}
     * @memberof SignRequestSignerInputAllOf
     */
    'page_index'?: number;
    /**
     * Whether this input was defined as read-only(immutable by signers) or not
     * @type {boolean}
     * @memberof SignRequestSignerInputAllOf
     */
    'read_only'?: boolean;
}

type SignRequestSignerInputAllOfTypeEnum = 'signature' | 'date' | 'text' | 'checkbox' | 'radio' | 'dropdown'
type SignRequestSignerInputAllOfContentTypeEnum = 'signature' | 'initial' | 'stamp' | 'date' | 'checkbox' | 'text' | 'full_name' | 'first_name' | 'last_name' | 'company' | 'title' | 'email' | 'attachment' | 'radio' | 'dropdown'


