/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Box\'s ready-sign link feature enables you to create a link to a signature request that you\'ve created from a template. Use this link when you want to post a signature request on a public form — such as an email, social media post, or web page — without knowing who the signers will be. Note: The ready-sign link feature is limited to Enterprise Plus customers and not available to Box Verified Enterprises.
 * @export
 * @interface SignTemplateAllOfReadySignLink
 */
export interface SignTemplateAllOfReadySignLink {
    /**
     * The URL that can be sent to signers.
     * @type {string}
     * @memberof SignTemplateAllOfReadySignLink
     */
    'url'?: string;
    /**
     * Request name.
     * @type {string}
     * @memberof SignTemplateAllOfReadySignLink
     */
    'name'?: string | null;
    /**
     * Extra instructions for all signers.
     * @type {string}
     * @memberof SignTemplateAllOfReadySignLink
     */
    'instructions'?: string | null;
    /**
     * The destination folder to place final, signed document and signing log. Only `ID` and `type` fields are required. The root folder, folder ID `0`, cannot be used.
     * @type {string}
     * @memberof SignTemplateAllOfReadySignLink
     */
    'folder_id'?: string | null;
    /**
     * Whether to disable notifications when a signer has signed.
     * @type {boolean}
     * @memberof SignTemplateAllOfReadySignLink
     */
    'is_notification_disabled'?: boolean;
    /**
     * Whether the ready sign link is enabled or not.
     * @type {boolean}
     * @memberof SignTemplateAllOfReadySignLink
     */
    'is_active'?: boolean;
}

