/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The user to assign the task to.
 * @export
 * @interface TaskAssignmentsAssignMultipleUsersRequestAssignTo
 */
export interface TaskAssignmentsAssignMultipleUsersRequestAssignTo {
    /**
     * The ID of the user to assign to the task.  To specify a user by their email address use the `login` parameter.
     * @type {string}
     * @memberof TaskAssignmentsAssignMultipleUsersRequestAssignTo
     */
    'id'?: string;
    /**
     * The email address of the user to assign to the task. To specify a user by their user ID please use the `id` parameter.
     * @type {string}
     * @memberof TaskAssignmentsAssignMultipleUsersRequestAssignTo
     */
    'login'?: string;
}

