/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FileActivityUser } from './file-activity-user';
import { TaskAssignees } from './task-assignees';
import { TaskFullAllOfPermissions } from './task-full-all-of-permissions';
import { TaskLinks } from './task-links';

/**
 * 
 * @export
 * @interface TaskFullAllOf
 */
export interface TaskFullAllOf {
    /**
     * Description of the task.
     * @type {string}
     * @memberof TaskFullAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {TaskAssignees}
     * @memberof TaskFullAllOf
     */
    'assigned_to'?: TaskAssignees;
    /**
     * When the task was completed.
     * @type {string}
     * @memberof TaskFullAllOf
     */
    'completed_at'?: string | null;
    /**
     * Rule to complete the task.
     * @type {string}
     * @memberof TaskFullAllOf
     */
    'completion_rule'?: TaskFullAllOfCompletionRuleEnum;
    /**
     * When the task was created.
     * @type {string}
     * @memberof TaskFullAllOf
     */
    'created_at'?: string;
    /**
     * 
     * @type {FileActivityUser}
     * @memberof TaskFullAllOf
     */
    'created_by'?: FileActivityUser;
    /**
     * When the task was modified.
     * @type {string}
     * @memberof TaskFullAllOf
     */
    'modified_at'?: string;
    /**
     * 
     * @type {TaskFullAllOfPermissions}
     * @memberof TaskFullAllOf
     */
    'permissions'?: TaskFullAllOfPermissions;
    /**
     * When the task progress was started.
     * @type {string}
     * @memberof TaskFullAllOf
     */
    'progress_at'?: string;
    /**
     * Status of the task
     * @type {string}
     * @memberof TaskFullAllOf
     */
    'status'?: TaskFullAllOfStatusEnum;
    /**
     * 
     * @type {TaskLinks}
     * @memberof TaskFullAllOf
     */
    'task_links'?: TaskLinks;
    /**
     * Type of the task
     * @type {string}
     * @memberof TaskFullAllOf
     */
    'task_type'?: TaskFullAllOfTaskTypeEnum;
}

type TaskFullAllOfCompletionRuleEnum = 'all_assignees' | 'any_assignee'
type TaskFullAllOfStatusEnum = 'approved' | 'completed' | 'in_progress' | 'not_started' | 'rejected'
type TaskFullAllOfTaskTypeEnum = 'approval' | 'general'


