/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TermsOfServiceCreateForEnterpriseAndTypeRequest
 */
export interface TermsOfServiceCreateForEnterpriseAndTypeRequest {
    /**
     * Whether this terms of service is active.
     * @type {string}
     * @memberof TermsOfServiceCreateForEnterpriseAndTypeRequest
     */
    'status': TermsOfServiceCreateForEnterpriseAndTypeRequestStatusEnum;
    /**
     * The type of user to set the terms of service for.
     * @type {string}
     * @memberof TermsOfServiceCreateForEnterpriseAndTypeRequest
     */
    'tos_type'?: TermsOfServiceCreateForEnterpriseAndTypeRequestTosTypeEnum;
    /**
     * The terms of service text to display to users.  The text can be set to empty if the `status` is set to `disabled`.
     * @type {string}
     * @memberof TermsOfServiceCreateForEnterpriseAndTypeRequest
     */
    'text': string;
}

type TermsOfServiceCreateForEnterpriseAndTypeRequestStatusEnum = 'enabled' | 'disabled'
type TermsOfServiceCreateForEnterpriseAndTypeRequestTosTypeEnum = 'external' | 'managed'


