/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The root-level record that is supposed to represent a single Terms of Service.
 * @export
 * @interface TermsOfServiceBase
 */
export interface TermsOfServiceBase {
    /**
     * The unique identifier for this terms of service.
     * @type {string}
     * @memberof TermsOfServiceBase
     */
    'id': string;
    /**
     * `terms_of_service`
     * @type {string}
     * @memberof TermsOfServiceBase
     */
    'type': TermsOfServiceBaseTypeEnum;
}

type TermsOfServiceBaseTypeEnum = 'terms_of_service'


