/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Tracking codes allow an admin to generate reports from the admin console and assign an attribute to a specific group of users. This setting must be enabled for an enterprise before it can be used.
 * @export
 * @interface TrackingCode
 */
export interface TrackingCode {
    /**
     * `tracking_code`
     * @type {string}
     * @memberof TrackingCode
     */
    'type'?: TrackingCodeTypeEnum;
    /**
     * The name of the tracking code, which must be preconfigured in the Admin Console
     * @type {string}
     * @memberof TrackingCode
     */
    'name'?: string;
    /**
     * The value of the tracking code
     * @type {string}
     * @memberof TrackingCode
     */
    'value'?: string;
}

type TrackingCodeTypeEnum = 'tracking_code'


