/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TrashWebLinkCreatedBy } from './trash-web-link-created-by';
import { TrashWebLinkModifiedBy } from './trash-web-link-modified-by';
import { TrashWebLinkOwnedBy } from './trash-web-link-owned-by';
import { TrashWebLinkParent } from './trash-web-link-parent';
import { TrashWebLinkPathCollection } from './trash-web-link-path-collection';

/**
 * Represents a trashed web link.
 * @export
 * @interface TrashWebLink
 */
export interface TrashWebLink {
    /**
     * The description accompanying the web link. This is visible within the Box web application.
     * @type {string}
     * @memberof TrashWebLink
     */
    'description'?: string;
    /**
     * `web_link`
     * @type {string}
     * @memberof TrashWebLink
     */
    'type'?: TrashWebLinkTypeEnum;
    /**
     * The unique identifier for this web link
     * @type {string}
     * @memberof TrashWebLink
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TrashWebLink
     */
    'sequence_id'?: string;
    /**
     * The entity tag of this web link. Used with `If-Match` headers.
     * @type {string}
     * @memberof TrashWebLink
     */
    'etag'?: string;
    /**
     * The name of the web link
     * @type {string}
     * @memberof TrashWebLink
     */
    'name'?: string;
    /**
     * The URL this web link points to
     * @type {string}
     * @memberof TrashWebLink
     */
    'url'?: string;
    /**
     * 
     * @type {TrashWebLinkParent}
     * @memberof TrashWebLink
     */
    'parent'?: TrashWebLinkParent;
    /**
     * 
     * @type {TrashWebLinkPathCollection}
     * @memberof TrashWebLink
     */
    'path_collection'?: TrashWebLinkPathCollection;
    /**
     * When this file was created on Box’s servers.
     * @type {string}
     * @memberof TrashWebLink
     */
    'created_at'?: string;
    /**
     * When this file was last updated on the Box servers.
     * @type {string}
     * @memberof TrashWebLink
     */
    'modified_at'?: string;
    /**
     * When this file was last moved to the trash.
     * @type {string}
     * @memberof TrashWebLink
     */
    'trashed_at'?: string | null;
    /**
     * When this file will be permanently deleted.
     * @type {string}
     * @memberof TrashWebLink
     */
    'purged_at'?: string | null;
    /**
     * 
     * @type {TrashWebLinkCreatedBy}
     * @memberof TrashWebLink
     */
    'created_by'?: TrashWebLinkCreatedBy;
    /**
     * 
     * @type {TrashWebLinkModifiedBy}
     * @memberof TrashWebLink
     */
    'modified_by'?: TrashWebLinkModifiedBy;
    /**
     * 
     * @type {TrashWebLinkOwnedBy}
     * @memberof TrashWebLink
     */
    'owned_by'?: TrashWebLinkOwnedBy;
    /**
     * The shared link for this bookmark. This will be `null` if a bookmark has been trashed, since the link will no longer be active.
     * @type {string}
     * @memberof TrashWebLink
     */
    'shared_link'?: string | null;
    /**
     * Whether this item is deleted or not. Values include `active`, `trashed` if the file has been moved to the trash, and `deleted` if the file has been permanently deleted
     * @type {string}
     * @memberof TrashWebLink
     */
    'item_status'?: TrashWebLinkItemStatusEnum;
}

type TrashWebLinkTypeEnum = 'web_link'
type TrashWebLinkItemStatusEnum = 'active' | 'trashed' | 'deleted'


