/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UploadSessionSessionEndpoints } from './upload-session-session-endpoints';

/**
 * An upload session for chunk uploading a file.
 * @export
 * @interface UploadSession
 */
export interface UploadSession {
    /**
     * The unique identifier for this session
     * @type {string}
     * @memberof UploadSession
     */
    'id'?: string;
    /**
     * `upload_session`
     * @type {string}
     * @memberof UploadSession
     */
    'type'?: UploadSessionTypeEnum;
    /**
     * The date and time when this session expires.
     * @type {string}
     * @memberof UploadSession
     */
    'session_expires_at'?: string;
    /**
     * The  size in bytes that must be used for all parts of of the upload.  Only the last part is allowed to be of a smaller size.
     * @type {number}
     * @memberof UploadSession
     */
    'part_size'?: number;
    /**
     * The total number of parts expected in this upload session, as determined by the file size and part size.
     * @type {number}
     * @memberof UploadSession
     */
    'total_parts'?: number;
    /**
     * The number of parts that have been uploaded and processed by the server. This starts at `0`.  When committing a file files, inspecting this property can provide insight if all parts have been uploaded correctly.
     * @type {number}
     * @memberof UploadSession
     */
    'num_parts_processed'?: number;
    /**
     * 
     * @type {UploadSessionSessionEndpoints}
     * @memberof UploadSession
     */
    'session_endpoints'?: UploadSessionSessionEndpoints;
}

type UploadSessionTypeEnum = 'upload_session'


