/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UploadsChunkedCreateSessionForUploadRequest
 */
export interface UploadsChunkedCreateSessionForUploadRequest {
    /**
     * The ID of the folder to upload the new file to.
     * @type {string}
     * @memberof UploadsChunkedCreateSessionForUploadRequest
     */
    'folder_id': string;
    /**
     * The total number of bytes of the file to be uploaded
     * @type {number}
     * @memberof UploadsChunkedCreateSessionForUploadRequest
     */
    'file_size': number;
    /**
     * The name of new file
     * @type {string}
     * @memberof UploadsChunkedCreateSessionForUploadRequest
     */
    'file_name': string;
}

