/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TrackingCode } from './tracking-code';
import { UsersUpdateManagedUserRequestNotificationEmail } from './users-update-managed-user-request-notification-email';

/**
 * 
 * @export
 * @interface UsersUpdateManagedUserRequest
 */
export interface UsersUpdateManagedUserRequest {
    /**
     * Set this to `null` to roll the user out of the enterprise and make them a free user
     * @type {string}
     * @memberof UsersUpdateManagedUserRequest
     */
    'enterprise'?: string | null;
    /**
     * Whether the user should receive an email when they are rolled out of an enterprise
     * @type {boolean}
     * @memberof UsersUpdateManagedUserRequest
     */
    'notify'?: boolean;
    /**
     * The name of the user
     * @type {string}
     * @memberof UsersUpdateManagedUserRequest
     */
    'name'?: string;
    /**
     * The email address the user uses to log in  Note: If the target user\'s email is not confirmed, then the primary login address cannot be changed.
     * @type {string}
     * @memberof UsersUpdateManagedUserRequest
     */
    'login'?: string;
    /**
     * The user’s enterprise role
     * @type {string}
     * @memberof UsersUpdateManagedUserRequest
     */
    'role'?: UsersUpdateManagedUserRequestRoleEnum;
    /**
     * The language of the user, formatted in modified version of the [ISO 639-1](https://raw.githubusercontent.com) format.
     * @type {string}
     * @memberof UsersUpdateManagedUserRequest
     */
    'language'?: string;
    /**
     * Whether the user can use Box Sync
     * @type {boolean}
     * @memberof UsersUpdateManagedUserRequest
     */
    'is_sync_enabled'?: boolean;
    /**
     * The user’s job title
     * @type {string}
     * @memberof UsersUpdateManagedUserRequest
     */
    'job_title'?: string;
    /**
     * The user’s phone number
     * @type {string}
     * @memberof UsersUpdateManagedUserRequest
     */
    'phone'?: string;
    /**
     * The user’s address
     * @type {string}
     * @memberof UsersUpdateManagedUserRequest
     */
    'address'?: string;
    /**
     * Tracking codes allow an admin to generate reports from the admin console and assign an attribute to a specific group of users. This setting must be enabled for an enterprise before it can be used.
     * @type {Array<TrackingCode>}
     * @memberof UsersUpdateManagedUserRequest
     */
    'tracking_codes'?: Array<TrackingCode>;
    /**
     * Whether the user can see other enterprise users in their contact list
     * @type {boolean}
     * @memberof UsersUpdateManagedUserRequest
     */
    'can_see_managed_users'?: boolean;
    /**
     * The user\'s timezone
     * @type {string}
     * @memberof UsersUpdateManagedUserRequest
     */
    'timezone'?: string;
    /**
     * Whether the user is allowed to collaborate with users outside their enterprise
     * @type {boolean}
     * @memberof UsersUpdateManagedUserRequest
     */
    'is_external_collab_restricted'?: boolean;
    /**
     * Whether to exempt the user from enterprise device limits
     * @type {boolean}
     * @memberof UsersUpdateManagedUserRequest
     */
    'is_exempt_from_device_limits'?: boolean;
    /**
     * Whether the user must use two-factor authentication
     * @type {boolean}
     * @memberof UsersUpdateManagedUserRequest
     */
    'is_exempt_from_login_verification'?: boolean;
    /**
     * Whether the user is required to reset their password
     * @type {boolean}
     * @memberof UsersUpdateManagedUserRequest
     */
    'is_password_reset_required'?: boolean;
    /**
     * The user\'s account status
     * @type {string}
     * @memberof UsersUpdateManagedUserRequest
     */
    'status'?: UsersUpdateManagedUserRequestStatusEnum;
    /**
     * The user’s total available space in bytes. Set this to `-1` to indicate unlimited storage.
     * @type {number}
     * @memberof UsersUpdateManagedUserRequest
     */
    'space_amount'?: number;
    /**
     * 
     * @type {UsersUpdateManagedUserRequestNotificationEmail}
     * @memberof UsersUpdateManagedUserRequest
     */
    'notification_email'?: UsersUpdateManagedUserRequestNotificationEmail | null;
    /**
     * An external identifier for an app user, which can be used to look up the user. This can be used to tie user IDs from external identity providers to Box users.  Note: In order to update this field, you need to request a token using the application that created the app user.
     * @type {string}
     * @memberof UsersUpdateManagedUserRequest
     */
    'external_app_user_id'?: string;
}

type UsersUpdateManagedUserRequestRoleEnum = 'coadmin' | 'user'
type UsersUpdateManagedUserRequestStatusEnum = 'active' | 'inactive' | 'cannot_delete_edit' | 'cannot_delete_edit_upload'


