/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TrackingCode } from './tracking-code';

/**
 * 
 * @export
 * @interface UserFullAllOf
 */
export interface UserFullAllOf {
    /**
     * The user’s enterprise role
     * @type {string}
     * @memberof UserFullAllOf
     */
    'role'?: UserFullAllOfRoleEnum;
    /**
     * Tracking codes allow an admin to generate reports from the admin console and assign an attribute to a specific group of users. This setting must be enabled for an enterprise before it can be used.
     * @type {Array<TrackingCode>}
     * @memberof UserFullAllOf
     */
    'tracking_codes'?: Array<TrackingCode>;
    /**
     * Whether the user can see other enterprise users in their contact list
     * @type {boolean}
     * @memberof UserFullAllOf
     */
    'can_see_managed_users'?: boolean;
    /**
     * Whether the user can use Box Sync
     * @type {boolean}
     * @memberof UserFullAllOf
     */
    'is_sync_enabled'?: boolean;
    /**
     * Whether the user is allowed to collaborate with users outside their enterprise
     * @type {boolean}
     * @memberof UserFullAllOf
     */
    'is_external_collab_restricted'?: boolean;
    /**
     * Whether to exempt the user from Enterprise device limits
     * @type {boolean}
     * @memberof UserFullAllOf
     */
    'is_exempt_from_device_limits'?: boolean;
    /**
     * Whether the user must use two-factor authentication
     * @type {boolean}
     * @memberof UserFullAllOf
     */
    'is_exempt_from_login_verification'?: boolean;
    /**
     * 
     * @type {object}
     * @memberof UserFullAllOf
     */
    'enterprise'?: object;
    /**
     * Tags for all files and folders owned by the user. Values returned will only contain tags that were set by the requester.
     * @type {Array<string>}
     * @memberof UserFullAllOf
     */
    'my_tags'?: Array<string>;
    /**
     * The root (protocol, subdomain, domain) of any links that need to be generated for the user
     * @type {string}
     * @memberof UserFullAllOf
     */
    'hostname'?: string;
    /**
     * Whether the user is an App User
     * @type {boolean}
     * @memberof UserFullAllOf
     */
    'is_platform_access_only'?: boolean;
    /**
     * An external identifier for an app user, which can be used to look up the user. This can be used to tie user IDs from external identity providers to Box users.
     * @type {string}
     * @memberof UserFullAllOf
     */
    'external_app_user_id'?: string;
}

type UserFullAllOfRoleEnum = 'admin' | 'coadmin' | 'user'


