/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FaFileVersion } from './fa-file-version';
import { FaFileVersionCreatedBy } from './fa-file-version-created-by';
import { FaFileVersionRestoredBy } from './fa-file-version-restored-by';
import { FaFileVersionTrashedBy } from './fa-file-version-trashed-by';

/**
 * 
 * @export
 * @interface VersionsActivityEnd
 */
export interface VersionsActivityEnd {
    /**
     * When the `file_version` object was created.
     * @type {string}
     * @memberof VersionsActivityEnd
     */
    'created_at'?: string;
    /**
     * 
     * @type {FaFileVersionCreatedBy}
     * @memberof VersionsActivityEnd
     */
    'created_by'?: FaFileVersionCreatedBy;
    /**
     * The unique identifier that represent a file version.
     * @type {string}
     * @memberof VersionsActivityEnd
     */
    'id': string;
    /**
     * Version number.
     * @type {number}
     * @memberof VersionsActivityEnd
     */
    'number'?: number;
    /**
     * When the `file_version` object was restored.
     * @type {string}
     * @memberof VersionsActivityEnd
     */
    'restored_at'?: string;
    /**
     * 
     * @type {FaFileVersionRestoredBy}
     * @memberof VersionsActivityEnd
     */
    'restored_by'?: FaFileVersionRestoredBy;
    /**
     * When the `file_version` object was trashed.
     * @type {string}
     * @memberof VersionsActivityEnd
     */
    'trashed_at'?: string;
    /**
     * 
     * @type {FaFileVersionTrashedBy}
     * @memberof VersionsActivityEnd
     */
    'trashed_by'?: FaFileVersionTrashedBy;
    /**
     * `file_version`
     * @type {string}
     * @memberof VersionsActivityEnd
     */
    'type'?: VersionsActivityEndTypeEnum;
}

type VersionsActivityEndTypeEnum = 'file_version'


