/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Array&lt;object&gt; } from './array&lt;object&gt;';
import { UserBase } from './user-base';

/**
 * A step in a Box Relay Workflow. Each flow contains a `Trigger` and a collection of Outcomes to perform once the conditions of a `Trigger` are met
 * @export
 * @interface WorkflowAllOfFlows
 */
export interface WorkflowAllOfFlows {
    /**
     * The identifier of the flow
     * @type {string}
     * @memberof WorkflowAllOfFlows
     */
    'id'?: string;
    /**
     * The flow\'s resource type
     * @type {string}
     * @memberof WorkflowAllOfFlows
     */
    'type'?: WorkflowAllOfFlowsTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof WorkflowAllOfFlows
     */
    'trigger'?: object;
    /**
     * 
     * @type {Array<object>}
     * @memberof WorkflowAllOfFlows
     */
    'outcomes'?: Array<object>;
    /**
     * When this flow was created
     * @type {string}
     * @memberof WorkflowAllOfFlows
     */
    'created_at'?: string;
    /**
     * 
     * @type {UserBase}
     * @memberof WorkflowAllOfFlows
     */
    'created_by'?: UserBase;
}

type WorkflowAllOfFlowsTypeEnum = 'flow'


