/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Box Relay Workflows are objects that represent a named collection of flows.  You application must be authorized to use the `Manage Box Relay` application scope within the developer console in order to use this resource.
 * @export
 * @interface WorkflowMini
 */
export interface WorkflowMini {
    /**
     * The description for a workflow.
     * @type {string}
     * @memberof WorkflowMini
     */
    'description'?: string;
    /**
     * The unique identifier for the workflow
     * @type {string}
     * @memberof WorkflowMini
     */
    'id'?: string;
    /**
     * `workflow`
     * @type {string}
     * @memberof WorkflowMini
     */
    'type'?: WorkflowMiniTypeEnum;
    /**
     * The name of the workflow
     * @type {string}
     * @memberof WorkflowMini
     */
    'name'?: string;
    /**
     * Specifies if this workflow is enabled
     * @type {boolean}
     * @memberof WorkflowMini
     */
    'is_enabled'?: boolean;
}

type WorkflowMiniTypeEnum = 'workflow'


