/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Workflow } from './workflow';
import { WorkflowsAllOf } from './workflows-all-of';
import { WorkflowsAllOf1 } from './workflows-all-of1';

/**
 * @type Workflows
 * A list of workflows.  You application must be authorized to use the `Manage Box Relay` application scope within the developer console in order to use this resource.
 * @export
 */
export type Workflows = WorkflowsAllOf & WorkflowsAllOf1;


