/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A file or folder for which a conflict was encountered, This object provides the type and identifier of the original item, as well as a mapping between its original name and it\'s new name as it will appear in the archive.
 * @export
 * @interface ZipDownloadNameConflictsInnerInner
 */
export interface ZipDownloadNameConflictsInnerInner {
    /**
     * The identifier of the item
     * @type {string}
     * @memberof ZipDownloadNameConflictsInnerInner
     */
    'id'?: string;
    /**
     * The type of this item
     * @type {string}
     * @memberof ZipDownloadNameConflictsInnerInner
     */
    'type'?: ZipDownloadNameConflictsInnerInnerTypeEnum;
    /**
     * The original name of this item
     * @type {string}
     * @memberof ZipDownloadNameConflictsInnerInner
     */
    'original_name'?: string;
    /**
     * The new name of this item as it will appear in the downloaded `zip` archive.
     * @type {string}
     * @memberof ZipDownloadNameConflictsInnerInner
     */
    'download_name'?: string;
}

type ZipDownloadNameConflictsInnerInnerTypeEnum = 'file' | 'folder'


