/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ZipDownloadNameConflictsInnerInner } from './zip-download-name-conflicts-inner-inner';

/**
 * Represents a successful request to create a `zip` archive of a list of files and folders.
 * @export
 * @interface ZipDownload
 */
export interface ZipDownload {
    /**
     * The URL that can be used to download the `zip` archive. A `Get` request to this URL will start streaming the items requested. By default, this URL is only valid for a few seconds, until the `expires_at` time, unless a download is started after which it is valid for the duration of the download.  It is important to note that the domain and path of this URL might change between API calls, and therefore it\'s important to use this URL as-is.
     * @type {string}
     * @memberof ZipDownload
     */
    'download_url'?: string;
    /**
     * The URL that can be used to get the status of the `zip` archive being downloaded. A `Get` request to this URL will return the number of files in the archive as well as the number of items already downloaded or skipped. By default, this URL is only valid for a few seconds, until the `expires_at` time, unless a download is started after which the URL is valid for 12 hours from the start of the download.  It is important to note that the domain and path of this URL might change between API calls, and therefore it\'s important to use this URL as-is.
     * @type {string}
     * @memberof ZipDownload
     */
    'status_url'?: string;
    /**
     * The time and date when this archive will expire. After this time the `status_url` and `download_url` will return an error.  By default, these URLs are only valid for a few seconds, unless a download is started after which the `download_url` is valid for the duration of the download, and the `status_url` is valid for 12 hours from the start of the download.
     * @type {string}
     * @memberof ZipDownload
     */
    'expires_at'?: string;
    /**
     * A list of conflicts that occurred when trying to create the archive. This would occur when multiple items have been requested with the same name.  To solve these conflicts, the API will automatically rename an item and return a mapping between the original item\'s name and its new name.  For every conflict, both files will be renamed and therefore this list will always be a multiple of 2.
     * @type {Array<Array<ZipDownloadNameConflictsInnerInner>>}
     * @memberof ZipDownload
     */
    'name_conflicts'?: Array<Array<ZipDownloadNameConflictsInnerInner>>;
}

