/*
Box Platform API

[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.

The version of the OpenAPI document: 2.0.0
Contact: devrel@box.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ZipDownloadRequestItemsInner } from './zip-download-request-items-inner';

/**
 * A request to create a `zip` archive to download
 * @export
 * @interface ZipDownloadRequest
 */
export interface ZipDownloadRequest {
    /**
     * A list of items to add to the `zip` archive. These can be folders or files.
     * @type {Array<ZipDownloadRequestItemsInner>}
     * @memberof ZipDownloadRequest
     */
    'items': Array<ZipDownloadRequestItemsInner>;
    /**
     * The optional name of the `zip` archive. This name will be appended by the `.zip` file extension, for example `January Financials.zip`.
     * @type {string}
     * @memberof ZipDownloadRequest
     */
    'download_file_name'?: string;
}

